### Business Python Interim Exam I (Take-Home) (50 points)

### Problem 1. (20 pts)
Write a function called stock_change() that accepts a list of stock values and determines if the average of the first half of the stocks is less than, or greater than, or equal to the average of the second half of the stock values. Assume that you will always have an even number of stocks in the list. Use print statements to communicate the results. 

"average stock value has decreased"    
"average stock value has increased"   
"average stock value is unchanged"    

In addition to the print statements, **return** a list containing the average of the lower half and the average of the upper half rounded to one decimal place. 

In [1]:
# Problem 1
def avg(az):
  return round(sum(az)/len(az),1)
def stock_change(data):
    x_az = avg(data[:int(len(data)/2)])
    y_az = avg(data[int(len(data)/2):])
    if x_az > y_az:
      print("average stock value has decreased")
    elif x_az < y_az:
      print("average stock value has increased")
    else:
      print("average stock value is unchanged")
    return [x_az,y_az]
      









In [9]:
# Test 1
stocks_dn=[4,3,6,4,1,2,3,2]
stock_change(stocks_dn)  # prints 'average stock value has decreased'

average stock value has decreased


[4.2, 2.0]

Expected Output
```
average stock value has decreased
[4.2, 2.0]
```

In [8]:
# Test 2
stocks_up=[2,3,2,4,3,4]
stock_change(stocks_up) # prints 'average stock value has increased'

average stock value has increased


[2.3, 3.7]

Expected Output
```
average stock value has increased
[2.3, 3.7]
```

In [7]:
# Test 3
stocks_e=[2,2,2,2,2,2,2,2,2,2]
stock_change(stocks_e) # prints 'average stock value is unchanged'

average stock value is unchanged


[2.0, 2.0]

Expected Output
```
average stock value is unchanged
[2.0, 2.0]
```

### Problem 2.  (20 pts)
Write a function called find_max() that accepts a dictionary of realtors and their home sale prices of the form,

```
realtors={
    "Stephanie": [320000, '460000', 220000, 279000],
    "Charles": [309000, 234500],
    "Donna": [762000, '455000', 135000],
    "Jenny": ['349000', 405000, 129000],
    "Mark": [156000, 239000, 360000, '890000']
}

```
and **returns** the maximum sale price and its data type (int). Note that some of the sale prices were recorded as strings. Make sure that your function can handle this case by including a step to convert all values into int data types. 

In [2]:
# problem 2 
def find_max(data):
    maxValue=0
    maxValueType=type(0)
    for realtor in data:
      realtor_values=data[realtor]
      for item in realtor_values:
        item = int(item)
        if type(item)==int:
          if item>int(maxValue):
            maxValue=item
            maxValueType=type(item)
        else:
          if int(item)>int(maxValue):
            maxValue=item
            maxValueType=type(item)
    return (maxValue,maxValueType)
    







In [6]:
realtors={
    "Stephanie": [320000, '460000', 220000, 279000],
    "Charles": [309000, 234500],
    "Donna": [762000, '455000', 135000],
    "Jenny": ['349000', 405000, 129000],
    "Mark": [156000, 239000, 360000, '890000']
}

# tests
find_max(realtors) # should return (890000, int) -- In CodeGrade (890000, <class 'int'>)

(890000, int)

### Problem 3.  (10 pts)
The program below needs some additional steps completed. The sample data is a nested dictionary. Your task is to fill in the indices necessary to extract the latitude ('lat'), longitude ('lng'), and  formatted address. Note that extra sample data will be use to test whether your function operates correctly on new data objects so make sure your program correctly references the function parameter.

In [3]:
# Problem 3 
def extract_location(data):

    # extract latitude, longitude and formatted address of the first matching location 
    # Fill in the blanks to make the code work
    #### YOUR CODE -- fill in the blanks ###
    latitude = data['results'][0]['geometry']['location']['lat']
    longitude = data['results'][0]['geometry']['location']['lng'] 
    formatted_address = data['results'][0]['formatted_address']

    # tests:
    print("latitude:", latitude)
    print("longitude:", longitude)
    print("address:", formatted_address)

In [4]:
# run this block to define the sample data
sample_data={"results":
        [
            {
            "formatted_address":"121 Presidents Dr, Amherst, MA 01003, USA",
            "geometry":{
                "location":{
                    "lat":42.386697,
                    "lng":-72.52489299999999
                    },
            "location_type":"ROOFTOP",
            "viewport":{
                "northeast":{
                    "lat":42.386697,
                    "lng":-72.52489299999999
                    },
                "southwest":{
                    "lat":42.386697,
                    "lng":-72.52489299999999,
                    }
                }
            },
            "place_id":"ChIJT2x8Q2BZwokRpBu2jUzX3dE",
            "plus_code":{
                "compound_code":"P27Q+MF Amherst, Massachusetts, United States",
                "global_code":"87G8P27Q+MF",
                }
            }
        ]
    }



In [5]:
# Test the function
extract_location(sample_data)

latitude: 42.386697
longitude: -72.52489299999999
address: 121 Presidents Dr, Amherst, MA 01003, USA


Expected Output
```
latitude: 42.386697
longitude: -72.52489299999999
address: 121 Presidents Dr, Amherst, MA 01003, USA
```